#schema.yml

version 2:

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: raw data of greenweez products
        columns:
          - name: products_id
            description: primary key identification
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: purchase price of the product
      - name: sales
        identifier: raw_gz_sales
        freshness:
          warn_after:
            count: 90
            period: day
        loaded_at_field: CAST(date_date AS TIMESTAMP)
        description: raw data of greenweez sales
        columns:
          - name: date_date
            description: date of sale
          - name: orders_id
            description: order id of the sale
          - name: pdt_id
            description: product id of the sale product
            tests:
              - not_null
          - name: revenue
            description: revenue of the sale
          - name: quantity
            description: quantity of the product sold
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: ship
        identifier: raw_gz_ship
        description: raw data of greenweez ship
        columns:
          - name: orders_id
            description: orders id of the shipped orders
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping fee of the order
          - name: shipping_fee_1
            description: shipping fee 2 of the order
          - name: logCost
            description: cost of the logistic
          - name: ship_Cost
            description: cost of the shipping
models:
  - name: int_sales_margin
    description: fusion des tables products and sales avec ajout de margin et purchase cost
    tests:
      - unique: 
          column_name: "(orders_id || '-' || products_id)"
    columns:
      - name: orders_id
        description: order id de la commande
        tests:
          - not_null
      - name: products_id
        description: product id du produit vendu
        tests:
          - not_null
      - name: purchase_price
        description: prix d'achat du produit vendu
        tests:
          - not_null
      - name: margin
        description: marge brute du produit. Différence entre le revenue et le prix d'achat
        tests:
          - not_null
      - name: purchase_cost
        description: cout d'achat du produit
        tests:
          - not_null
      - name: date_date
        description: date de la commande
        tests:
          - not_null
      - name: revenue
        description: revenue de la commande / produit
        tests:
          - not_null
      - name: quantity
        description: quantité de produit vendu
        tests:
          - not_null
  - name: int_orders_margin
    description: agréggation par order_id et date
    columns:
      - name: date_date
        description: date de la commande
        tests:
          - not_null
      - name: orders_id
        description: order id de la commande
        tests:
          - not_null
          - unique
      - name: revenue
        description: total de revenue par commande et par jour
        tests:
          - not_null
      - name: quantity
        description: total de quantity de produits vendus par commande
        tests:
          - not_null
      - name: purchase_cost
        description: total du cout d'achat des articles présent dans la commande
        tests:
          - not_null
      - name: margin
        description: total de la marge par commande et par jour
        tests:
          - not_null
  - name: int_orders_operational
    description: ajout de la table ship et calcul des operational margin
    columns:
      - name: orders_id
        description: order id de la commande
        tests:
          - unique
          - not_null
      - name: date_date
        description: date de la commande
        tests:
          - not_null
      - name: revenue
        description: revenue par commande
        tests:
          - not_null
      - name: operational_margin 
        description: marge opérationnelle par commande
        tests:
          - not_null
      - name: quantity
        description: quantité de produits par commande
        tests:
          - not_null
      - name: margin
        description: marge brute par commande
        tests:
          - not_null
      - name: purchase_cost
        description: cout d'achat par commande
        tests:
          - not_null
      - name: shipping_fee
        description: cout d'envoi factué au client
        tests:
          - not_null
      - name: ship_cost
        description: cout d'envoi payé par la compagnie
        tests:
          - not_null
      - name: log_cost
        description: cout logistique
        tests:
          - not_null
  - name: finance_days
    description: aggrégation par jour et création des KPI pertinents
    columns:
      - name: date_date
        description: date de la commande / vente
        tests:
          - not_null
          - unique
      - name: nb_transactions
        description: nombre de transactions total sur une journée
        tests:
          - not_null
      - name: total_revenue
        description: CA total sur une journée
        tests:
          - not_null
      - name: avg_basket
        description: panier moyen par jour
        tests:
          - not_null
      - name: operational_margin
        description: total de la marge operationnelle à la journée
        tests:
          - not_null
      - name: total_purchase_cost
        description: total des cout d'achat des produits vendus sur la journée
        tests:
          - not_null
      - name: total_shipping_fee
        description: total des frais d'envoi facturé au client à la journée
        tests:
          - not_null
      - name: total_log_cost 
        description: total des couts d'envoi payé par la compagnie
        tests:
          - not_null
      - name: total_product_sold
        description: quantité totale de produits vendus
        tests:
          - not_null
  